FROM sirensolutions/avatica-tls-server:latest

# Download the PostgreSQL JDBC driver to the /home/avatica/jdbc directory so that it will be included in the classpath
ADD --chown=avatica https://jdbc.postgresql.org/download/postgresql-42.2.23.jar /home/avatica/jdbc
