#!/usr/bin/env groovy
library 'jenkins-lib'

pipeline {

  agent {
    kubernetes {
      cloud getKubernetesClusterName()
      yaml readK8sConfig('build', '4Gi', '1')
    }
  }

  options {
    timestamps()
    ansiColor('xterm')
  }

  stages {
    stage ('Checkout') {
      steps {
        checkout scm
      }
    }

    stage ('Test') {
      steps {
        sh 'mvn test'
      }
    }

    stage ('Package') {
      steps {
        sh 'mvn package -DskipTests'
      }
    }
  }

}
